# Generated by Django 5.1.7 on 2025-03-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Transaction',
        ),
    ]
