# Generated by Django 5.1.7 on 2025-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0005_currencybalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencybalance',
            name='share_portfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
